### ISSUE TITLE
help regarding the dataset

### ISSUE THREAD

**Issue by notmanan** [Jackustc/Question-Level-Feature-Extraction-on-DAIC-WOZ-dataset#3]
Hi! This is not really an issue, I needed help acquiring the DAIC-WOZ dataset. We're working on an ML project that would run on the DAIC-WOZ dataset but the http://dcapswoz.ict.usc.edu/ site seems to be down or something. If you could share the email address that was on the site earlier to obtain the DAIC-WOZ dataset, that would be awesome. Thanks!

**Comment by A-kali** [comment]
I can't open this website either. If you get the data, can you send me a copy?

**Comment by Jackustc** [comment]
I can open the link and copy the download instruction from  http://dcapswoz.ict.usc.edu/ as follows.

Download

To be able to download the DAIC-WOZ database, please download (http://dcapswoz.ict.usc.edu/wwwutil_files/DAICWOZDEP_EULA.pdf), sign and return the agreement form to this e-mail (boberg@ict.usc.edu) address. Please note that, unfortunately, due to consent constraints we are only allowed to distribute the data to academics and other non-profit researchers. Please use your academic e-mail address when requesting the data download.
